services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: robotic_unscrewing
    container_name: devcontainer
    network_mode: "host" 
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro 
      - /home/abdelrahman/circu_li_ion_case_study/robotic_unscrewing/src:/home/ubuntu/ros2_ws/src/

    entrypoint: ["/bin/bash"]
    tty: true
    stdin_open: true
